const LOGIN_REDUCERS = {
    SET_EMAIL: 'SET_EMAIL',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_EMAIL_ERROR: 'SET_EMAIL_ERROR',
    SET_PASSWORD_ERROR: 'SET_PASSWORD_ERROR'
}
export default LOGIN_REDUCERS;